go.mod
go.sum

This reverts commit fcd66c5c65ef2e5487868dc0587b83b612fbc033.
* [Fix ...]
Fix #XXX

Revert "chore(deps): bump fatih/color from 1.15.0 to 1.16.0 (#16)"

---

go.mod
go.sum
pkg/file/readfile.go

Only if stdin and stderr are both TTY. To inform users input is expected, instead of appearing to "hang".
related to https://github.com/Kong/deck/pull/1115

chore(cli): notify user when reading from stdin

---

.github/dependabot.yml
go.mod
go.sum

Downgrade the github.com/fatih/color library to 1.15. See prior reasoning in https://github.com/Kong/deck/pull/1109. Unfortunately dependabot upgraded it. This also adds config to not do that again.
Avoids an issue with logs formatting improperly pending future removal of the library: https://github.com/Kong/go-database-reconciler/issues/22

chore: downgrade and pin color

---

.github/dependabot.yml
.github/workflows/checks.yaml
.github/workflows/integration-enterprise.yaml
.github/workflows/integration.yaml
go.mod
go.sum

Re https://github.com/Kong/go-database-reconciler/pull/21#issuecomment-1836186240 why things merged without passing tests, well, we simply have no required tests! We have a require status checks branch protection rule with no required status checks configured, same as deck did. I'm not sure if anything was preventing merges with failures in the past.
This cannibalizes a similar [KIC workflow](https://github.com/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/checks.yaml) that aggregates required test workflows into a single `passed` status. Note that we still need to add this to the branch protection rules after for it to have effect.

chore: add a test aggregation workflow

---

pkg/file/writer.go
tests/integration/sync_test.go
tests/integration/testdata/sync/029-plugin-scoped-to-cg-route/kong.yaml

fix: consumer-group scope doesn't work with multiple nesting

---

pkg/file/builder.go
pkg/file/builder_test.go

Kong Gateway supports different schemas for different router versions. On the other hand, Konnect can support only one schema including all fields from 'traditional' and 'expressions' router schemas. This may be problematic when it comes to defaults injection, because the defaults for the 'traditiona' router schema can be wrongly injected into the 'expressions' route configuration.
Here we make sure that only the fields that are supported for a given router version are set in the route configuration.
* [Fix ...]
Fix #XXX

fix: correctly handle route schema defaults with Konnect

---

.ci/clean_kong.sh
.ci/lib.sh
.ci/setup_kong.sh
.ci/setup_kong_ee.sh

The integration cleanup script (`.ci/clean_kong.sh`) had a couple warts:
* the `--filter Name=<name>` arg performs substring matching, so if you have an unrelated container named `kong-foo` running, it would enter the wrong branch and throw an error
* manually tracking docker resources for cleanup gets pretty tedious
I updated it to filter resources based on a known docker label instead.
This involved touching a few different files to add docker labels and such, so I wound up DRY-ing up some of the CI setup scripts along the way.

ci: fix `make clean` and refactor

---

pkg/dump/dump.go

This updates the business logic that is used to decide if (wasm) filter chains are supported by Kong. Instead of relying on the caller to set `dump.Config.IsFilterChainsSupported`, we check the error response code from `GET /filter-chains` and decide how to proceed from there.
---
See also: https://github.com/Kong/deck/pull/987 specifically: https://github.com/Kong/deck/pull/987#discussion_r1629376245
KAG-4005

fix: detect filter chain support from API response

---

pkg/file/codegen/main.go
pkg/file/kong_json_schema.json
pkg/file/readfile_test.go
pkg/file/testdata/valid/filter-chains.yaml

This relaxes the JSON schema for filter chain entities to not require `name` or `id`. Filter chains are _always_ associated with a service or a route and therefore do not require a name/id for indexing.
KAG-4005

fix: do not require name/id for filter-chain entities

---

pkg/file/template.go
pkg/file/template_test.go

default remains DECK_ so no functional changes to existing code. also adds tests for rendering files.

feat: make the DECK_ envvar prefix configurable

---

.github/workflows/integration-enterprise.yaml
.github/workflows/integration.yaml
pkg/state/consumer_group_consumers.go

This commit makes lookups for consumer-group's consumers more performant by adding indexes in the in-memory db, instead of relying on "manual" looping which is very expensive when several thousands of consumers exist.
Testing is provided by existing tests.
* [Fix ...]
Fix #XXX

fix: improve lookup of consumer-groups' consumers

---

pkg/file/builder.go
pkg/file/builder_test.go

When syncing a target with a compressed IPv6 (for example `[2001:db8:fd73::e]:1326`) decK can successfully create it but it fails to detect its existence when pulling the config from the API because the CP expands the address (for example to `[2001:0db8:fd73:0000:0000:0000:0000:000e]:1326`) causing decK to attempt to recreate the target and failing because the target already exists.
This commit fixes this by using some helpers to expand the ipv6 before trying to sync/dump.
* [Fix ...]
Fix #XXX

fix: correctly compare compressed/expanded ipv6 in targets

---

pkg/dump/dump.go
pkg/utils/types.go
tests/integration/dump_test.go

Add custom entities in `dump.Get` to support dumping custom entities
* [Feature] Support dumping custom entities
Fix #110

add custom entities to dump.Get

---

pkg/file/builder.go

At the moment, when we run deck file render, all routes get `regex_priority` field. This field is not applicable in the case of expression routes. A rendered file from deck containing expression routes, thus failed to sync directly.
This change ensures that expression routes do not get the fields of traditional routes.
Test for change added in separate branch. 
Fix [#1250](https://github.com/Kong/deck/issues/1250)
Manually tested locally on Kong Gateway running via Docker. Tested this with both traditional router and expression router.

fix: Fix yaml files rendered for expression routes

---

pkg/file/builder.go
pkg/file/builder_test.go

Test for PR: https://github.com/Kong/go-database-reconciler/pull/116
One test for ingest routes are separated into two to deal with different kinds of routes - expression and traditional.
Added assertion to ensure that `regex_priority` is not present in expression route but present in the traditional routes.

test: Valid expression routes building

---

pkg/file/builder.go
pkg/file/builder_test.go
pkg/utils/utils.go

v3.7.0 added changes to allow traditional route fields with expression routes, thus making expression router a superset of traditional router.
Ref: https://github.com/Kong/kong/pull/12667
Thus, keys like regex_priority are not supported in versions lesser than 3.7.0.
Added a gating logic in state builder for the necessary changes and fixed tests.
Fix #1250
* Added gating logic in state builder
* Fixed tests for the same
Fix [#1250](https://github.com/Kong/deck/issues/1250)

Fix: Expression route handling fix for Konnect and < v3.7.0

---

pkg/diff/diff.go

Fixes a bug in the event sender. The original structure of this section meant that GDR only sent change events to the channel if they had encountered in an error. This did not make [the KIC DB mode error event generator](https://github.com/Kong/kubernetes-ingress-controller/pull/5785) unhappy, but did not work very well for https://github.com/Kong/kubernetes-ingress-controller/pull/6131, as it did not see most change events. Whoops.
This assigns the error to the event regardless of whether it's nil or not (it'll either populate or just remain nil) and sends the event off before checking for a non-nil error and performing the error return.
After this change, the channel will receive successful events also. This was the original intent, but the breakage went unnoticed til I tried to actual …

fix: send change events always

---

.github/workflows/integration-enterprise.yaml
.github/workflows/integration.yaml

According to https://docs.konghq.com/gateway/latest/support-policy/#older-versions there's a handful of versions that already reached EOL.
This PR removes them from the test matrix.
* [Fix ...]
Fix #XXX

chore(ci): remove EOLd versions from test matrix

---

pkg/state/types.go
pkg/state/types_test.go

Prior to this fix, deck was reporting the plugins as global even if a consumer-group was attached to them. This was only a output problem, not a association problem. The fix checks if a consumer-group exists or not before reporting any plugin as global.
Fixes: https://github.com/Kong/deck/issues/1005

fix: plugin shown as global despite a consumer-group present

---

pkg/diff/diff.go
pkg/types/core.go
pkg/types/plugin.go
tests/integration/sync_test.go
tests/integration/testdata/sync/034-fill-auto-oauth2/kong.yaml

fix(diff): support auto fields
call the new utils function FillPluginsDefaultsAutoFields from  go-kong
to ensure auto fields are considered when doing the diff
fix(crud): detect operation correctly
fixes a bug that was introduced in
e72f4c2de6609998d5e5671e14a9f7c0cd6a4c3e where noops were still detected
as updates. That happened because of a check happening in plugin.go that
detected the crud operation based on a diff.
When done without considering default/auto fields, this check would see
differences where there were none. This resulted in unnecessary updates
to the DB and wrong diff strings during `sync` and `diff`.
This commit adds defaults/auto fields to the configuration used for that
diff.
* [Fix ...]
[KAG-5210](https://konghq.atlassian.net/browse/KAG-5210) …

 fix(diff): support auto fields

---

.golangci.yml
pkg/file/builder.go
pkg/file/writer.go
pkg/state/document_test.go
pkg/state/filter_chain_test.go
pkg/state/license_test.go
pkg/state/plugin_test.go
pkg/state/rbac_endpoint_permission_test.go
pkg/state/rbac_role_test.go
pkg/state/route_test.go
pkg/state/service_package_test.go
pkg/state/service_test.go
pkg/state/service_version_test.go
pkg/state/sni_test.go

The `exportloopref` linter is no longer needed due to a change in how loop variables work in Go 1.22+
See https://go.dev/blog/loopvar-preview for more information
* Replaced `exportloopref` with `copyloopvar` linter

chore(lint): Switch to copyloopvar linter for Go 1.22+

---

.github/workflows/checks.yaml
scripts/_lib.sh
scripts/update-deepcopy-gen.sh
scripts/verify-codegen.sh
scripts/verify-deepcopy-gen.sh

Fix code generation and add it to CI.
Without this change we get:
```
make update-codegen ; make verify-codegen
./scripts/update-deepcopy-gen.sh
unknown flag: --input-dirs
Usage of deepcopy-gen:
--add_dir_header                   If true, adds the file directory to the header of the log messages
--alsologtostderr                  log to standard error as well as files (no effect when -logtostderr=true)
--bounding-dirs strings            Comma-separated list of import paths which bound the types for which deep-copies will be generated.
--go-header-file string            the path to a file containing boilerplate header text; the string "YEAR" will be replaced with the current 4-digit year
--log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0) …
```

ci: fix codegen

---

pkg/file/builder.go
tests/integration/sync_test.go
tests/integration/testdata/sync/036-scoped-plugins-validation/3x/consumer-plugins.yaml
tests/integration/testdata/sync/036-scoped-plugins-validation/3x/route-plugins.yaml
tests/integration/testdata/sync/036-scoped-plugins-validation/3x/service-plugins.yaml
tests/integration/testdata/sync/036-scoped-plugins-validation/consumer-plugins.yaml
tests/integration/testdata/sync/036-scoped-plugins-validation/route-plugins.yaml
tests/integration/testdata/sync/036-scoped-plugins-validation/service-plugins.yaml

As of now, while using deck to create a
route-scoped plugin with a `service` field
defined, the sync goes through the first
time but errors out subsequently. Under a
route, we do not want the user to add the
`service` field for a plugin. Thus, we are
checking for this specific scenario and
erroring out, instead of letting the sync
action go through.
For: https://github.com/Kong/deck/issues/1353

fix: returning a validation error in case of wrong configuration.

---

.github/dependabot.yml
.github/workflows/codeql.yaml

Add codeql code scanning.
Remove docker dependabot config as there's no Dockerfile in this repo.
* [Fix ...]
Fix #XXX

chore(ci): add codeql code scanning

---

pkg/types/degraphql_route.go

Konnect APIs don't support Service.Name to perform operations
on degraphql_routes. Thus, stripping the name reference.
Currently, we do the same for routes as well.
https://github.com/Kong/go-database-reconciler/blob/main/pkg/types/route.go#L19
* [Fix ...]
Fix #XXX

fix: strip service name from dql_routes for konnect apis

---

pkg/file/builder.go
pkg/file/builder_test.go
pkg/file/types.go
tests/integration/sync_test.go
tests/integration/testdata/sync/037-degraphql-routes/kong-complex-query.yaml
tests/integration/testdata/sync/037-degraphql-routes/kong-wrong-svc-config.yaml
tests/integration/testdata/sync/037-degraphql-routes/kong.yaml

While creating a degraphql-route using deck, we were specifying
service field as a string. This is different than how deck usually
handles references. So, inorder to comply with the current deck
format, we are changing the service reference to a dict.
* fix: changed dql routes format to show dict for service.
* tests: fixed test files based on new dql-routes format.
* fix: added validations to ensure correct format for configs is passed.
* tests: added tests to handle for required fields/format.
Pre-req for https://github.com/Kong/deck/pull/1505

fix: changed dql routes format to show dict for service

---

pkg/file/types.go
tests/integration/sync_test.go

In case of a reset and re-sync, an id
field with service can lead to an error.
The PR also cleans up the duplicate
test found here: https://github.com/Kong/go-database-reconciler/pull/187#discussion_r1941023028
For https://github.com/Kong/go-database-reconciler/issues/193

fix: removed service id from dql_routes dump

---

pkg/dump/dump.go

With the kong version check in place in dump config,
Konnect was receiving errors.
We do not need that check for
Konnect, thus bypassing it.
This was found via tests failing here: https://github.com/Kong/deck/actions/runs/13177537568/job/36783633324?pr=1518
Also, removing the stray comment pointed out here: https://github.com/Kong/go-database-reconciler/pull/191#discussion_r1944489775

fix: dump config fix for Konnect

---

pkg/file/writer.go

For https://github.com/Kong/deck/issues/1517

fix: fixed dump config to show select tags when consumer-group-policy-overrides is set

---

pkg/dump/dump.go
pkg/file/builder.go

dump config comprised of custom-entities: degraphql_routes. Since, custom-entities are EE feature, a forbidden error from the gateway was causing OSS ops to fail
For https://github.com/Kong/deck/issues/1522

fix: fixed usage for deck oss

---

pkg/state/builder.go
tests/integration/sync_test.go
tests/integration/testdata/sync/038-partials/kong-update.yaml

Update operations on partials were failing
while using Konnect as a backend. This was
because update payload included `created_at`
field which is read-only for Konnect. The
same does not fail with the gateway. Thus,
we are zeroing out the timestamp field
for partial while building the state.
More: https://kongstrong.slack.com/archives/C0663589T3R/p1742810047116689?thread_ts=1742795974.288409&cid=C0663589T3R
For #166

fix: fixed partial entity updates while syncing with Konnect

---

.github/workflows/checks.yaml

Currently we do not have the user and token defined for dependabot's scope so just skip the enterprise tests for dependabot PRs until that's resolved. 
* [Fix ...]
Fix #XXX

fix(ci): fix dependabot PRs by skipping the enterprise tests when DockerHub tokens is missing

---

pkg/state/types.go
pkg/state/types_test.go
tests/integration/diff_test.go
tests/integration/testdata/diff/004-plugin-update/initial-ip-restriction.yaml
tests/integration/testdata/diff/004-plugin-update/protocol-initial-order-plugins.yaml
tests/integration/testdata/diff/004-plugin-update/protocol-reordered-plugins.yaml

The issue seems to be due to the order of `protocols` defined for the ip-restriction plugin.
When we sync for the second time, if the protocols are not declared in the file we are trying to sync, we load defaults from the `/schemas/plugins/ip-restriction` endpoint on konnect - which returns them in a [given order](https://github.com/Kong/kong-ee/blob/c31e7045db6a111c254e6609c1945e9320f6d661/kong/plugins/ip-restriction/schema.lua#L14).
However, when we fetch the current state, konnect returns the plugin with the protocols sorted.
This is leading to the differ considering them unequal.
Relevant discussion: https://kongstrong.slack.com/archives/CQK8J4VN3/p1743588627387659
* [fix: ip restriction plugin diff](https://github.com/Kong/go-database-reconciler/pull/240/commits/c006d430e75c12537b324d …

fix: ip restriction plugin diff

---

pkg/cprint/color.go
pkg/types/basicauth.go
pkg/types/consumer_group_plugin.go

For: https://github.com/Kong/deck/issues/1588

fix: moving warnings from stdout to stderr so as to not break json ouput

---

pkg/file/builder.go
pkg/file/builder_test.go
tests/integration/sync_test.go
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-consumer-groups-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-consumer-groups-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-consumers-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-consumers-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-routes-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-routes-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-services-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-services-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-consumer-groups-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-consumer-groups-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-consumers-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-consumers-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-routes-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-routes-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-services-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-services-via-names.yaml

Till deck v1.42.1, references in plugin
config worked fine if IDs were passed.
If names were passed, the first sync
went fine, but all the next syncs
showed unique key violation error.
This was because names were getting
resolved as IDs and then processed for
fetching the plugin from currentState,
which gave a 404. Thus, a new plugin
was getting created each time, leading
to uniqueness violation error.
With deck v1.43.0, we were not
allowing nested foreign keys. We are 
relaxing this constraint here:
https://github.com/Kong/go-database-reconciler/pull/249
Thus, necessary changes are added 
to make this work properly with named references.
For https://github.com/Kong/deck/issues/1595

fix: named foreign key references work properly for plugins

---

pkg/file/builder.go
pkg/file/builder_test.go
tests/integration/sync_test.go
tests/integration/testdata/diff/004-plugin-update/protocol-initial-order-plugins.yaml
tests/integration/testdata/diff/004-plugin-update/protocol-reordered-plugins.yaml
tests/integration/testdata/sync/036-scoped-plugins-validation/3x/consumer-plugins.yaml
tests/integration/testdata/sync/036-scoped-plugins-validation/3x/route-plugins.yaml
tests/integration/testdata/sync/036-scoped-plugins-validation/3x/service-plugins.yaml
tests/integration/testdata/sync/036-scoped-plugins-validation/consumer-plugins.yaml
tests/integration/testdata/sync/036-scoped-plugins-validation/route-plugins.yaml
tests/integration/testdata/sync/036-scoped-plugins-validation/service-plugins.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-consumer-groups-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-consumer-groups-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-consumers-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-consumers-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-routes-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-routes-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-services-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/1_1/kong-services-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-consumer-groups-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-consumer-groups-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-consumers-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-consumers-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-routes-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-routes-via-names.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-services-via-ids.yaml
tests/integration/testdata/sync/040-plugins-nested-foreign-keys/kong3x-services-via-names.yaml

We are retaining the constraint only if
the foreign keys are of same type.
e.g; if service.plugins[i] has a service
field, it would error out
For https://github.com/Kong/deck/issues/1593

fix: removing constraint for foreign keys inside scoped plugin config.

---

pkg/file/builder.go

REopen from previous [PR](https://github.com/Kong/go-database-reconciler/pull/144) as some bug happened with the fork
When running `deck diff` on Kong 3.4.x we can see below error: 
```
1 unsupported routes' paths format with Kong version 3.0
or above were detected. Some of these routes are (not an exhaustive list):
ecf1297e-95e2-4e86-9384-86c892f941a7
Please upgrade your configuration to account for 3.0
breaking changes using the following command:
```
As there are hundred of regex route and the error causing the pipeline to stop. There are no way currently to determine the problematic route.
There is a workaround for this issue by running `deck convert` but I would like to see the affected route first before running the command.
* Add extra path information in 3.4.x compatibility warn

feat: Adds paths information in 3.4.x compatibility warn

---

tests/integration/sync_test.go

Some tests got accidentally deleted during this revert: https://github.com/Kong/go-database-reconciler/pull/254/files
Adding them back.

tests: adding plugin sync with foreign refs tests

---

pkg/state/builder.go
tests/integration/apply_test.go
tests/integration/test_utils.go
tests/integration/testdata/apply/001-custom-entities/initial-state.yaml
tests/integration/testdata/apply/001-custom-entities/partial-update.yaml

In this PR, we are ignoring the error returned from `ensureService` for Degraphql routes - similar to how other entities behave so that gateway apply command is fixed for custom entities.
https://github.com/Kong/deck/issues/1568

fix: partial apply for custom entities

---

pkg/file/builder.go
pkg/file/builder_test.go
tests/integration/sync_test.go
tests/integration/testdata/sync/038-partials/ill-formatted-partial.yaml
tests/integration/testdata/sync/038-partials/nested-plugin-ill-formatted-partial.yaml
tests/integration/testdata/sync/038-partials/nested-plugin-partial-no-ids.yaml
tests/integration/testdata/sync/038-partials/nested-plugin-partial-not-exists.yaml
tests/integration/testdata/sync/038-partials/nested-plugin-partials.yaml
tests/integration/testdata/sync/038-partials/plugin-partial-no-ids.yaml

Partial linking for nested plugins was not
working well as it was unaccounted for.
Now, `ingestPlugin()` method links the
partials to the plugins. As this method
is used by other entities that may have a
nested plugin, it would be ensured that all
entities with a nested plugin that use a
partial are able to link it to one.
For https://github.com/Kong/deck/issues/1649

fix: fetch partials in case of nested plugins

---

pkg/state/types.go

`reflect.DeepEqual()` function returns false
in cases when tags are empty or not in the
same order. Thus, deck marks this as an
update and shows a false diff.
Thus, adding the tag handling code in all
places where it seems missing.
For https://github.com/Kong/deck/issues/1674

fix: deck marks false diff due to empty or unordered tags

---

go.mod

This resolves a few known vulnerabilities -[GO-2025-3751](https://pkg.go.dev/vuln/GO-2025-3751), [GO-2025-3750](https://pkg.go.dev/vuln/GO-2025-3750) and [GO-2025-3749](https://pkg.go.dev/vuln/GO-2025-3749)
https://github.com/Kong/deck/issues/1688

chore: bump go version to 1.24.4

---

.github/workflows/integration-enterprise.yaml
tests/integration/sync_test.go

In this PR, we are adding Enterprise Gateway v3.11 to the test matrix

chore: add 3.11 to test matrix

---

pkg/types/target.go
tests/integration/sync_test.go
tests/integration/testdata/sync/004-create-upstream-and-target/kong-before.yaml
tests/integration/testdata/sync/004-create-upstream-and-target/kong3x-before.yaml

Following this issue #322 
This pull request leverage the new [go-kong v0.67.0](https://github.com/Kong/go-kong/releases/tag/v0.67.0) [Target Update API](https://github.com/Kong/go-kong/blob/v0.67.0/kong/target_service.go#L27) instead of doing a Delete/Create.
* Add support for the Target ``Update`` API, enabling updates to Upstream Targets.
Fix #322 
Tried to follow the current testing done for this part of the code. There are no unit test, and integration tests didn't covered the Target Update apis. I added integration tests to cover the Target Update API and tested it with several version (the one reported in the test comments). 
Ran the full integration test for all the version reported in the [integration.yaml](https://github.com/Kong/go-database-reconciler/blob/v1.24.3/.github/workfl …

leverage go-kong new target update api

---

go.mod
go.sum
pkg/file/builder.go
pkg/file/builder_test.go
tests/integration/diff_test.go
tests/integration/sync_test.go
tests/integration/testdata/sync/015-consumer-groups/kong-consumer-1.yaml
tests/integration/testdata/sync/015-consumer-groups/kong-consumer-2.yaml

Syncing and diffing with default_lookup_tags
for consumer-groups was errorneous. While
dumping config, we would dump all consumers
in case of default-lookup tags. Thus, in case of
serial syncing of consumers, previous consumers
would end up getting deleted.
This fix ensures that no unexpected deletions occur
while using consumer-group lookups.
Issue is described in detail in
the doc and FTI below:
[Document](https://konghq.atlassian.net/wiki/spaces/~7120204d7e8997ba384e09b1eee597d986a1dc/pages/4618027031/Default+LookUp+Tags+for+Deck)
[FTI](https://konghq.atlassian.net/browse/FTI-6754)
For https://github.com/Kong/deck/issues/1617

fix: build behaviour for consumers in case of defaultLookup tags used for consumer-groups

---

pkg/state/types.go
tests/integration/diff_test.go
tests/integration/sync_test.go
tests/integration/testdata/sync/003-create-a-plugin/plugin-nested-array-reordered.yaml
tests/integration/testdata/sync/003-create-a-plugin/plugin-nested-array.yaml

This change ensures that plugins
can be configured with nested arrays.
A test-case is added that shows two ways
of adding array of arrays.
Way 1:
```
config:
fieldName:
- - item1
- - item2
```
Way 2:
```
config:
fieldName:
- ['item1']
- ['item2']
```
Both ways are valid yaml and supported by deck.
For https://github.com/Kong/deck/issues/1740

feat: support nested array in plugin config
